FROM openjdk:8-jre-alpine
VOLUME /tmp
 RUN   apk update \
  &&   apk add ca-certificates wget \
  &&   update-ca-certificates \
  &&   wget https://oss.sonatype.org/content/repositories/public/io/hawt/hawtio-app/2.0.0/hawtio-app-2.0.0.jar
ENTRYPOINT ["java","-jar","hawtio-app-2.0.0.jar","--port","8090"]
